"use client"

import { memo, useState } from "react"

// ─── Scope ───────────────────────────────────────────────────────────────────

const MOUNT_ITEMS = new Set([
  "TV/Monitor",
  "Art/Picture Frame",
  "Floating Shelves",
  "Mirror",
  "Light Fixture",
])

// Blender-rendered PNGs — generated by running npm run render:<name>
const MOUNT_RENDERS: Record<string, string> = {
  "TV/Monitor":        "/assets/renders/tv-monitor.png",
  "Art/Picture Frame": "/assets/renders/art-frame.png",
  "Floating Shelves":  "/assets/renders/floating-shelves.png",
  "Mirror":            "/assets/renders/mirror.png",
  "Light Fixture":     "/assets/renders/light-fixture.png",
}

export function isMountItem(option: string): boolean {
  return MOUNT_ITEMS.has(option)
}

// ─── MountHybridPreview ───────────────────────────────────────────────────────

export const MountHybridPreview = memo(function MountHybridPreview({
  option,
  className,
}: {
  option: string
  className?: string
}) {
  const [imgLoaded, setImgLoaded] = useState(false)
  const renderSrc = MOUNT_RENDERS[option]

  if (!renderSrc) return null

  return (
    <div className={`relative w-full h-full ${className ?? ""}`}>
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src={renderSrc}
        alt={option}
        className="absolute inset-0 w-full h-full pointer-events-none select-none"
        style={{
          objectFit: "contain",
          opacity: imgLoaded ? 1 : 0,
          transition: "opacity 0.55s ease",
        }}
        onLoad={() => setImgLoaded(true)}
      />
    </div>
  )
})
